package cli

import (
	"bufio"
	"fmt"
	"os"
	"strings"
	"syscall"
	"time"

	"github.com/user/auth-cli-system/internal/api/handlers"
	"golang.org/x/term"
)

// ANSI color codes
const (
	ColorReset  = "\033[0m"
	ColorRed    = "\033[31m"
	ColorGreen  = "\033[32m"
	ColorYellow = "\033[33m"
	ColorBlue   = "\033[34m"
	ColorPurple = "\033[35m"
	ColorCyan   = "\033[36m"
	ColorBold   = "\033[1m"
	ColorDim    = "\033[2m"
)

// PrintSuccess prints a formatted success message
func PrintSuccess(format string, a ...interface{}) {
	msg := fmt.Sprintf(format, a...)
	fmt.Printf("%s✔ %s%s\n", ColorGreen, msg, ColorReset)
}

// PrintError prints a formatted error message
func PrintError(format string, a ...interface{}) {
	msg := fmt.Sprintf(format, a...)
	fmt.Printf("%s✖ Error: %s%s\n", ColorRed, msg, ColorReset)
}

// PrintInfo prints a formatted informational message
func PrintInfo(format string, a ...interface{}) {
	msg := fmt.Sprintf(format, a...)
	fmt.Printf("%sℹ %s%s\n", ColorCyan, msg, ColorReset)
}

// PrintWarning prints a formatted warning message
func PrintWarning(format string, a ...interface{}) {
	msg := fmt.Sprintf(format, a...)
	fmt.Printf("%s⚠ %s%s\n", ColorYellow, msg, ColorReset)
}

// ReadLine reads a line from stdin, trimming trailing newlines
func ReadLine(prompt string) (string, error) {
	fmt.Print(prompt)
	reader := bufio.NewReader(os.Stdin)
	line, err := reader.ReadString('\n')
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(line), nil
}

// ReadPassword securely prompts and reads a password without echoing characters to screen
func ReadPassword(prompt string) (string, error) {
	fmt.Print(prompt)
	stdinFd := int(syscall.Stdin)

	if term.IsTerminal(stdinFd) {
		bytePassword, err := term.ReadPassword(stdinFd)
		fmt.Println() // print newline after user presses Enter
		if err != nil {
			return "", err
		}
		return strings.TrimSpace(string(bytePassword)), nil
	}

	// Fallback for non-interactive / piped environments
	reader := bufio.NewReader(os.Stdin)
	line, err := reader.ReadString('\n')
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(line), nil
}

// DisplayUserDetails renders the required user information in a clear, formatted box
func DisplayUserDetails(user *handlers.UserSummary) {
	lastLoginStr := "First login (no previous session)"
	if user.LastLoginAt != nil {
		lastLoginStr = user.LastLoginAt.Format(time.RFC1123)
	}

	sessionExpiryStr := "N/A"
	if user.SessionExpiresAt != nil {
		sessionExpiryStr = user.SessionExpiresAt.Format(time.RFC1123)
		remaining := time.Until(*user.SessionExpiresAt).Round(time.Minute)
		if remaining > 0 {
			sessionExpiryStr += fmt.Sprintf(" (in ~%v)", remaining)
		}
	}

	mfaFormatted := fmt.Sprintf("%sDISABLED%s", ColorYellow, ColorReset)
	if strings.EqualFold(user.MFAStatus, "enabled") {
		mfaFormatted = fmt.Sprintf("%sENABLED%s", ColorGreen, ColorReset)
	}

	fmt.Println()
	fmt.Printf("%s┌────────────────────────────────────────────────────────────┐%s\n", ColorCyan, ColorReset)
	fmt.Printf("%s│                    CURRENT USER PROFILE                    │%s\n", ColorCyan, ColorReset)
	fmt.Printf("%s├────────────────────────────────────────────────────────────┤%s\n", ColorCyan, ColorReset)
	fmt.Printf("│ %sUsername:%s          %-39s │\n", ColorBold, ColorReset, user.Username)
	fmt.Printf("│ %sRegistration Date:%s %-39s │\n", ColorBold, ColorReset, user.RegistrationDate.Format("2006-01-02 15:04:05 MST"))
	fmt.Printf("│ %sMFA Status:%s        %-48s │\n", ColorBold, ColorReset, mfaFormatted)
	fmt.Printf("│ %sSession Expiry:%s    %-39s │\n", ColorBold, ColorReset, sessionExpiryStr)
	fmt.Printf("│ %sLast Login:%s        %-39s │\n", ColorBold, ColorReset, lastLoginStr)
	fmt.Printf("%s└────────────────────────────────────────────────────────────┘%s\n", ColorCyan, ColorReset)
	fmt.Println()
}

// DisplayMFASetup presents the TOTP enrollment details clearly
func DisplayMFASetup(secret, uri string) {
	fmt.Println()
	fmt.Printf("%s====================== 2FA SETUP ======================%s\n", ColorBold, ColorReset)
	fmt.Printf("1. Open Google Authenticator (or any RFC 6238 TOTP app).\n")
	fmt.Printf("2. Add a new account manually using this Secret Key:\n\n")
	fmt.Printf("   %s%s%s\n\n", ColorBold+ColorGreen, secret, ColorReset)
	fmt.Printf("3. Or import using the standard Key URI:\n")
	fmt.Printf("   %s%s%s\n\n", ColorDim, uri, ColorReset)
	fmt.Printf("4. Enter the 6-digit verification code generated by the app.\n")
	fmt.Printf("%s======================================================%s\n", ColorBold, ColorReset)
	fmt.Println()
}
